# Generated by Django 4.1.6 on 2023-02-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='missing_img.jpg', upload_to='', verbose_name='Картинка (необязательно)'),
        ),
    ]
