# Generated by Django 4.1.6 on 2023-02-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_comments_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_changelog', models.CharField(max_length=200, verbose_name='Заголовок changelog')),
                ('desc_changelog', models.CharField(max_length=200, verbose_name='Описание changelog')),
                ('date_changelog', models.DateField(verbose_name='Дата changelog')),
            ],
        ),
    ]
