# Generated by Django 4.1.6 on 2023-02-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_changelogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelogpost',
            name='date_changelog',
            field=models.DateTimeField(verbose_name='Дата changelog'),
        ),
    ]
